### ISSUE TITLE
Agregar y modificar casos de uso con las recomendaciones despues de las sesiones

### ISSUE THREAD

**Issue by natiicruuz** [natiicruuz/24-25-IdSw1-SDR#18]
Abarcar dudas y realizar correcciones con @mmasias sobre los casos de uso.

**Comment by natiicruuz** [comment]
@mmasias 

Según las dudas mencionadas en la [sesión 2](https://github.com/natiicruuz/24-25-IdSw1-SDR/blob/main/SesionesDeRequisitado/Sesion2.md)

**1. Con respecto al diagrama de clases:**
- Se aclaró la jerarquía apuntando a la guía como el documento final, el producto final.
- Hay dos guías docentes, la versión digital y versión física, por lo cual se tendrá que adaptar el diagrama de clases.

Lo que conversamos es que en el diagrama de clases hablamos sobre la **plantilla multititulación** y cómo puede que no sea necesario agregarlo, a no ser que aclaremos que lo que llamamos **Guía** en el diagrama de clases es la versión digital y la plantilla seria la guía en formato físico como tal.

_Lo que nos surge la duda es cómo se puede pensar en aquellas asignaturas que comparten distintos grados (titulaciones) y que, al final, sus objetivos (contenido dinámico) puede cambiar dependiendo de la titulación_

**2. Compuertas lógicas en diagramas de estados**
Se nos preguntó si dentro de los diagramas de estados deberían ir compuertas lógicas que nos lleven a los distintos estados. No sabemos si eso debería ir en los diagramas de estados o mejor en el detallado de los casos de uso como tal y en el diagrama de contexto.

Por ejemplo: en la sección de [casos de uso](https://github.com/natiicruuz/24-25-IdSw1-SDR/blob/main/ModeloDelDominio/modeloDelDominio.md), se nos pregunta si, por ejemplo, si en la parte de revisión, debería haber una compuerta lógica que pregunte si el contenido está correcto o no y de ahí sacar los siguientes posibles estados.

**Comment by mmasias** [comment]
![IMG_20241122_115924.jpg](https://github.com/user-attachments/assets/b41a05a1-7260-4ff0-a845-3d69aa793735)

**Comment by natiicruuz** [comment]
@BrendaLopes @MikaOT @sara-patino 

**1. Con respecto al diagrama de clases:**

Hablamos de que se tiene la **asignatura**, se tiene la **titulación** y se tiene la **Guía docente** (entiéndase Guía docente como la guía digital, no el PDF que se muestra al final).

Se podría pensar que la **asignatura** junto con la **titulación** es lo que genera el **contenido de la guía docente**. Entonces, realmente, para manejar los temas de las titulaciones que comparten asignaturas, podemos analizar estos dos puntos y así generamos una guía docente específica para cada titulación. 

La imagen de arriba dice que el contenido de las asignaturas es lo que genera el contenido de las guías docentes y que dependiendo de la titulación, se agrega cierto contenido específico, y con estas dos ideas, se termina de generar el contenido total de la Guía docente. 

**2. Compuertas lógicas en diagramas de estados**
En los diagramas de estados como tal, no es necesario poner las compuertas lógicas, pero sí es importante refinar un par de diagramas para que los estados fluyan naturalmente y se entienda sin la necesidad de una compuerta lógica.

En el _detallado de casos de uso_, ahí sí se hacen las compuertas lógicas, pero igual hay que refinar los estados y la manera en la que está redactado para que se entienda el flujo sin problemas. También es importante quitar aquellas “líneas” que no tengan que ver específicamente con ese caso de uso, es decir, que involucran a otro actor a hacer una acción externa. 

¿Me confirman que lo leyeron y se entiende?

**Comment by BrendaLopes** [comment]
@mmasias Lo acabo de ver! Gracias por el feedback, echare un vistazo a los diagramas y hablaré con el resto del grupo para que los adaptamos de acuerdo con los conceptos que has mencionado.

**Comment by sara-patino** [comment]
Genial! Lo platicamos en persona para quedar de acuerdo en el orden jerárquico adecuado.
