### ISSUE TITLE
Encontrar Actores y Casos De Uso

### ISSUE THREAD

**Issue by natiicruuz** [natiicruuz/24-25-IdSw1-SDR#9]

**Comment by natiicruuz** [comment]
Hace falta agregarlo pero con Plantuml https://plantuml.com/es-dark/use-case-diagram

Me encargo yo y lo revisamos juntos @MikaOT :D

**Comment by natiicruuz** [comment]
Ya he revisado, sin embargo, considero que el sistema no es un actor. En todo caso, las funcionalidades que tiene el sistema son acciones que cada actor puede hacer dependiendo de su rol.

**Comment by natiicruuz** [comment]
Propongo los siguientes casos de uso, quitando el sistema como actor y agregando algunos adicionales.

**Editar Contenido de la Guía**

Actor: Profesor
Descripción: El profesor actualiza el contenido de una guía docente para una asignatura específica.
Objetivo: Mantener el contenido actualizado y relevante para los estudiantes.

**Aprobar o Rechazar Contenido**

Actor: Director de Grado
Descripción: Revisión y decisión sobre el contenido de la guía docente.
Objetivo: Asegurar que el contenido cumple con los estándares académicos.

**Supervisar Guías Docentes**

Actor: Técnico de Calidad
Descripción: Revisión de guías para verificar el cumplimiento de los estándares de calidad.
Objetivo: Garantizar uniformidad en formato y calidad de las guías.

**Auditar Guías Docentes**

Actor: Dirección de Calidad
Descripción: Realiza auditorías sobre las guías docentes, revisando la calidad del contenido.
Objetivo: Asegurar la máxima calidad y adherencia a los objetivos institucionales.

**Utilizar Plantilla Multititulación**

Actor: Técnico de Calidad
Descripción: Selección y aplicación de una plantilla común para varias titulaciones.
Objetivo: Asegurar consistencia en el formato de las guías de diferentes titulaciones.

**Generar Nueva Versión de la Guía**

Actor: Técnico de Calidad
Descripción: Solicita al sistema la creación de una nueva versión de la guía para registrar cambios y ediciones.
Objetivo: Facilitar la trazabilidad de modificaciones en el tiempo.

**Asignar Guía a Titulación**

Actor: Técnico de Calidad
Descripción: Establece la vinculación de una guía docente a una titulación específica.
Objetivo: Organizar las guías de acuerdo con cada titulación.

**Asignar Asignatura a Titulación**

Actor: Técnico de Calidad
Descripción: Asocia cada asignatura con su titulación correspondiente.
Objetivo: Mantener la estructura de programas académicos dentro del sistema.

**Publicar Guía Docente**

Actor: Director de Grado
Descripción: Autoriza y finaliza la publicación de una guía docente para que esté disponible en el panel universitario.
Objetivo: Permitir que los estudiantes accedan a la versión aprobada y oficial.

**Verificar Cumplimiento con Memoria Verificada**

Actor: Dirección de Calidad
Descripción: Revisión de las guías para confirmar la adherencia a la memoria verificada, utilizando una API de verificación.
Objetivo: Asegurar que las guías se ajusten a los requisitos y lineamientos institucionales.

**Comment by natiicruuz** [comment]
Supervisar seria un estado, el director de grado verifica las guias y como resultado el estado es supervisar.  Auditar titulacion

cambiar y/o revisar concepto de memoria verificada, porque al final es una memoria por titulación.

director de grado tambien debe tener la potestad de editar GD.

director de grado cambiar aprobar/rechazar por validar

**Comment by BrendaLopes** [comment]
Tecnico de calidad - asignar guia a profesor. Supervisar no hace falta, seria una responsabilidad de direccion de calidad.
Director de Grado - aprovar/rechazar = revisar
